#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

## https://github.com/openebs/litmus/blob/master/apps/percona/workload/test_vars.yml 
test_name=$(${utils_path}/generate_test_name testcase=percona-loadgen metadata="")

#########################
## INFRA DEPENDENCIES  ##
#########################

${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, navigate to litmus root 
git clone https://github.com/openebs/litmus.git
cd litmus 

#######################
## JOB DEPENDENCIES  ##
#######################

sleep 180 #wait till deployer is initiated, else job wont be found
${utils_paths}/litmus_job_runner label='app:percona-deployment' jobfile=NA action='wait_on_job' cr=NA

############################
## LITMUS PRECONDITIONING ##
############################

cp apps/percona/workload/run_litmus_test.yml run_test.yml

#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='loadgen:percona-loadjob' jobfile=run_test.yml action='run_job_to_completion' cr=NA
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}
