#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

## https://github.com/openebs/litmus/blob/master/apps/percona/liveness/test_vars.yml
run_id=""; test_name=$(${utils_path}/generate_test_name testcase=percona-liveness metadata=${run_id})
      
########################
## INFRA DEPENDENCIES ##
########################

observer_node=$(${utils_path}/setup_dependencies litmus-test)

## Clone the litmus repo,navigate to litmus root 
git clone https://github.com/openebs/litmus.git
cd litmus 

#######################
## JOB DEPENDENCIES  ##
#######################

sleep 180 #wait until deployer is initiated, else job won't be found
${utils_path}/litmus_job_runner label='app:percona-deployment' jobfile=NA action='wait_on_job' cr=NA

############################
## LITMUS PRECONDITIONING ##
############################

cp apps/percona/liveness/run_litmus_test.yml run_test.yml

sed -i -e "s|#nodeSelector|nodeSelector|g" \
-e "s|#  kubernetes.io/hostname:|  kubernetes.io/hostname: ${observer_node}|g" run_test.yml

#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."
# Unlike other tests, liveness gitlab runners need to exit immediately after verifying "liveness
# launch success" via CR. This calls for us to perform a one-time confirmation of liveness pod.
${utils_path}/litmus_job_runner label='liveness:percona-liveness' jobfile=run_test.yml action='run_and_wait_on_result_cr' cr=${test_name}
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}
