#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

## https://github.com/openebs/litmus/blob/master/apps/percona/liveness/test_vars.yml
run_id=""; test_name=$(${utils_path}/generate_test_name testcase=percona-liveness metadata=${run_id})
      
########################
## INFRA DEPENDENCIES ##
########################

observer_node=$(${utils_path}/setup_dependencies litmus-test)

## Clone the litmus repo,navigate to litmus root 
git clone https://github.com/openebs/litmus.git
cd litmus 

#######################
## JOB DEPENDENCIES  ##
#######################

${utils_paths}/wait_on_job label='app:percona-deployment'

############################
## LITMUS PRECONDITIONING ##
############################

cp apps/percona/liveness/run_litmus_test.yml run_test.yml

sed -i -e "s|#nodeSelector|nodeSelector|g" \
-e "s|#  kubernetes.io/hostname:|  kubernetes.io/hostname: ${observer_node}|g" run_test.yml

#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='liveness:percona-liveness' job=run_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}
