#!/bin/bash

litmus_job_label_key=$(echo $1 | cut -d "=" -f 2 | cut -d ":" -f 1)
litmus_job_label_value=$(echo $1 | cut -d "=" -f 2 | cut -d ":" -f 2)

jobNameCmd="kubectl get jobs -n litmus --no-headers -o jsonpath='{.items[?(@.metadata.labels.${litmus_job_label_key}==\"${litmus_job_label_value}\")].metadata.name}'"

job_name=$(eval ${jobNameCmd}); retcode=$?
${utils_path}/error_handler ${retcode} msg="Unable to find litmusbook, exiting" action="exit"

litmusPodCmd="kubectl get pod --no-headers -n litmus -o jsonpath='{.items[?(@.metadata.labels.job-name==\"${job_name}\")].metadata.name}'"
litmus_pod=$(eval ${litmusPodCmd}); retcode=$?
${utils_path}/error_handler ${retcode} msg="Unable to find litmus test runner pod, exiting" action="exit"

## TODO: Consider cases where litmus pod is evicted

while [[ ! $(eval ${containerStateCmd}) =~ 'terminated' ]]; do
  sleep 1 
done 

while [[ $(eval ${jobStateCmd}) =~ 'Running' ]]; do
   sleep 1
done

echo "Litmus test run Job has completed"
