#!/bin/bash

set -e

echo "AWS Cluster Cleaning"

# ------------------------- Setting aws credentails -------------------------------

export AWS_ACCESS_KEY_ID=$AC_ID
export AWS_SECRET_ACCESS_KEY=$AC_KEY
export AWS_DEFAULT_REGION=eu-west-2
export AWS_DEFAULT_OUTPUT=json

# ---- Creating Directory and storing necessary data inside it --------------------
mkdir /tmp/aws
cat aws/cluster/id.csv > /tmp/aws/id.csv
cat aws/cluster/cluster_name.csv >/tmp/aws/cluster_name.csv
cat aws/cluster/volume-id >/tmp/aws/volume-id

aws_cluster_name=$(cat /tmp/aws/cluster_name.csv | cut -d ":" -f 2); echo ${aws_cluster_name}

# ---- Cloning litmus repository for cleaning AWS cluster and pre-requisite--------
git clone https://github.com/openebs/litmus.git
cd litmus/k8s/aws/k8s-installer

# ---------------------- Deleting AWS cluster -------------------------------------
ansible-playbook delete-aws-cluster.yml -v

# ---------------------- Deleting AWS pre-requisite -------------------------------
ansible-playbook delete-pre-requisite.yml -v

# ---------------------- Deleting Disks ------------------------------------------#
cd ../ebs-volumes
ansible-playbook delete-ebs-volume.yml --extra-vars "cluster_name=nodes.k8s-${aws_cluster_name}.k8s.local"
