#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

test_name=$(${utils_path}/generate_test_name testcase=cstor-disk-pool-provision metadata="")
 
###################
## DEPENDENCIES  ##
###################

${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, navigate to litmus root 
git clone https://github.com/openebs/litmus.git
cd litmus

#######################
## JOB DEPENDENCIES  ##
#######################

sleep 180 #wait until deployer is initiated, else job wont be found
${utils_path}/litmus_job_runner label='provider:openebs-setup' jobfile=NA action='wait_on_job' cr=NA

############################
## LITMUS PRECONDITIONING ##
############################

cp providers/cstor/cstor-disk-pool/run_litmus_test.yml run_test.yml

#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='app:cstor-disk-pool-provision' jobfile=run_test.yml action='run_job_to_completion' cr=NA
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}

